apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
  namespace: database
  labels:
    app: database-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
